"""
SAARTHI AI — Recommendation Routes
Fetch recommendations, get explainability, view action preview, confirm via MPIN.
This is the critical path for the human-in-the-loop flow.
"""
from __future__ import annotations

from fastapi import APIRouter, Path

from backend.models.recommendation import (
    ActionPreviewResponse,
    ConfirmRecommendationRequest,
    RecommendationListResponse,
)
from backend.security.human_in_loop import human_in_loop_gate
from backend.security.mpin_gate import mpin_gate
from backend.services.audit_service import audit_service
from backend.models.audit_log import AuditStep, AuditStatus
from backend.utils.error_handlers import RecommendationNotFoundError
from backend.utils.logging_config import get_logger

logger = get_logger(__name__)
router = APIRouter()

# In-memory recommendation store (production: Redis/DB)
# Populated by agents as they generate recommendations
_recommendation_store: dict[str, dict] = {}


def store_recommendation(rec_dict: dict) -> None:
    """Called by agents to register a recommendation for retrieval."""
    _recommendation_store[rec_dict["recommendation_id"]] = rec_dict


@router.get("/{customer_id}", response_model=RecommendationListResponse)
async def get_recommendations(customer_id: str):
    """
    Fetch active recommendations for a customer.
    These are generated by MARGDARSHAN/MITRA/SAATHI agents.
    """
    recs = [
        r for r in _recommendation_store.values()
        if r.get("customer_id") == customer_id.upper()
        and r.get("status") in ("pending", "shown")
    ]

    return RecommendationListResponse(
        customer_id=customer_id.upper(),
        total=len(recs),
        recommendations=recs,
    )


@router.get("/{recommendation_id}/why")
async def get_why_explanation(recommendation_id: str):
    """
    Return the 'Why am I seeing this?' explanation for a recommendation.
    Explainable AI requirement.
    """
    rec = _recommendation_store.get(recommendation_id)
    if not rec:
        raise RecommendationNotFoundError(
            message=f"Recommendation '{recommendation_id}' not found"
        )

    return {
        "recommendation_id": recommendation_id,
        "why_explanation": rec.get("why_explanation", ""),
        "explainability": rec.get("explainability"),
        "data_used": rec.get("explainability", {}).get("data_used", []) if rec.get("explainability") else [],
        "agent_source": rec.get("agent_source"),
    }


@router.post("/{recommendation_id}/action-preview", response_model=ActionPreviewResponse)
async def show_action_preview(recommendation_id: str):
    """
    Show the Action Preview for a recommendation.
    This is Step 2 of the human-in-the-loop chain.
    Advances the recommendation from GENERATED → PREVIEW_SHOWN.
    """
    rec = _recommendation_store.get(recommendation_id)
    if not rec:
        raise RecommendationNotFoundError(
            message=f"Recommendation '{recommendation_id}' not found"
        )

    customer_id = rec["customer_id"]

    # Advance human-in-loop state
    human_in_loop_gate.advance_to_preview(recommendation_id, customer_id)

    # Update recommendation status
    rec["status"] = "action_preview"
    _recommendation_store[recommendation_id] = rec

    # Log audit step
    audit_service.log_step(
        customer_id=customer_id,
        step=AuditStep.ACTION_PREVIEW,
        agent=rec.get("agent_source"),
        recommendation_id=recommendation_id,
    )

    return ActionPreviewResponse(
        recommendation_id=recommendation_id,
        customer_id=customer_id,
        action_preview=rec["action_preview"],
        why_explanation=rec["why_explanation"],
        next_step="Verify with MPIN to proceed",
    )


@router.post("/{recommendation_id}/confirm")
async def confirm_recommendation(
    recommendation_id: str,
    request: ConfirmRecommendationRequest,
):
    """
    Confirm a recommendation with MPIN.
    Steps: MPIN verification → advance to execute → return success.
    This is the final gate before execution.
    """
    rec = _recommendation_store.get(recommendation_id)
    if not rec:
        raise RecommendationNotFoundError(
            message=f"Recommendation '{recommendation_id}' not found"
        )

    customer_id = rec["customer_id"]

    # Step 1: Verify MPIN (this raises MPINVerificationError on failure)
    mpin_gate.verify(customer_id, request.mpin)

    # Step 2: Advance to MPIN_VERIFIED stage
    human_in_loop_gate.advance_to_mpin(recommendation_id, customer_id)

    # Step 3: Advance to EXECUTED (unlocks execution)
    human_in_loop_gate.advance_to_execute(recommendation_id, customer_id)

    # Update recommendation status
    rec["status"] = "accepted"
    _recommendation_store[recommendation_id] = rec

    # Log MPIN verification
    audit_service.log_step(
        customer_id=customer_id,
        step=AuditStep.MPIN_VERIFICATION,
        agent=rec.get("agent_source"),
        recommendation_id=recommendation_id,
        status=AuditStatus.SUCCESS,
        metadata={"method": "mpin"},
    )

    # Log execution complete
    audit_service.log_step(
        customer_id=customer_id,
        step=AuditStep.EXECUTION_COMPLETE,
        agent=rec.get("agent_source"),
        recommendation_id=recommendation_id,
        metadata={"product_type": rec.get("product_type")},
    )

    return {
        "status": "confirmed",
        "recommendation_id": recommendation_id,
        "message": "Your request has been submitted successfully! SBI will process it within 2 hours.",
        "product": rec.get("action_preview", {}).get("product"),
    }
