"""
SAARTHI AI — Orchestrator
LangGraph-based multi-agent orchestrator.
Routes events/intents to the appropriate agent based on EVENT_AGENT_MAP.

Follows Kamal's LangGraph architecture decisions.
This module can be swapped with a full StateGraph implementation
when Kamal finalises the orchestration strategy.

Current implementation: lightweight async dispatcher with LangGraph-compatible
StateGraph stub ready for extension.
"""
from __future__ import annotations

from typing import Any, TypedDict

from backend.agents import margdarshan_agent, mitra_agent, saathi_agent
from backend.models.event import Event
from backend.models.recommendation import FallbackResponse, Recommendation
from backend.services.event_engine import event_engine
from backend.utils.constants import (
    AGENT_MARGDARSHAN,
    AGENT_MITRA,
    AGENT_SAATHI,
    EVENT_AGENT_MAP,
)
from backend.utils.logging_config import get_logger

logger = get_logger(__name__)


# ── LangGraph State Schema ─────────────────────────────────────────────────

class OrchestratorState(TypedDict):
    """State passed through the LangGraph workflow."""
    customer_id: str
    event: dict[str, Any]
    assigned_agent: str | None
    result: dict[str, Any] | None
    error: str | None


# ── Routing Logic ──────────────────────────────────────────────────────────

def route_event_to_agent(event: Event) -> str:
    """
    Determine which agent should handle a given event.
    Uses EVENT_AGENT_MAP from constants.py.
    Returns agent name string.
    """
    agent = EVENT_AGENT_MAP.get(event.event_type, AGENT_MARGDARSHAN)
    logger.info(
        "orchestrator_routing",
        event_type=event.event_type,
        agent=agent,
        event_id=event.event_id,
    )
    return agent


async def dispatch(
    customer_id: str,
    event: Event,
) -> Recommendation | FallbackResponse:
    """
    Main dispatcher: routes event to the correct agent and awaits result.

    Args:
        customer_id: Customer to process.
        event: The classified event.

    Returns:
        Recommendation or FallbackResponse from the agent.
    """
    agent_name = route_event_to_agent(event)

    logger.info(
        "orchestrator_dispatching",
        customer_id=customer_id,
        event_id=event.event_id,
        agent=agent_name,
    )

    try:
        if agent_name == AGENT_MARGDARSHAN:
            result = await margdarshan_agent.run_margdarshan(customer_id, event)

        elif agent_name == AGENT_MITRA:
            result = await mitra_agent.run_mitra(customer_id, event)

        elif agent_name == AGENT_SAATHI:
            result = await saathi_agent.run_saathi(customer_id, event)

        else:
            logger.warning("orchestrator_unknown_agent", agent=agent_name)
            result = await margdarshan_agent.run_margdarshan(customer_id, event)

        # Mark the event as processed
        event_engine.mark_processed(
            event_id=event.event_id,
            result=f"recommendation_generated by {agent_name}",
            agent=agent_name,
        )

        return result

    except Exception as e:
        logger.error(
            "orchestrator_dispatch_failed",
            customer_id=customer_id,
            event_id=event.event_id,
            agent=agent_name,
            error=str(e),
        )
        event_engine.mark_failed(event.event_id, str(e))
        raise
